Compatibility with sonata admin 4
goldbroker/cmf pull request #4
Opened 2024-07-31 14:40 UTC by piero-hgt

2024-08-05 16:39 UTC, patrick-benoit commented on src/Bundle/MediaBundle/Doctrine/Phpcr/File.php
> +    public function setParentDocument($parent): \Doctrine\ODM\PHPCR\Document\AbstractFile
Petit problème de Rector qui met encore les FQN ?

2024-08-06 08:09 UTC, patrick-benoit commented on src/Bundle/SonataPhpcrAdminIntegrationBundle/Admin/Routing/RouteAdmin.php
>          /** @var $route Route */
`?Route` ?

2024-08-06 08:15 UTC, patrick-benoit commented on src/Bundle/TreeBrowserBundle/Resources/build/webpack.config.js
> +            // },
Lignes commentées inutiles

2024-08-06 08:15 UTC, patrick-benoit commented on src/Bundle/TreeBrowserBundle/Resources/build/webpack.config.js
> +            // 'jquery-ui' : path.join(__dirname, 'node_modules/jquery-ui/dist/jquery-ui.js'),
Idem

2024-08-06 08:31 UTC, patrick-benoit commented on src/Sonata/DoctrinePHPCRAdminBundle/Model/ModelManager.php
> +//    }
Petit oubli de nettoyage

2024-08-06 08:41 UTC, patrick-benoit requested changes
Quelques truc à nettoyer, mais rien de choquant

2024-08-06 15:06 UTC, piero-hgt commented on src/Bundle/MediaBundle/Doctrine/Phpcr/File.php
> +    public function setParentDocument($parent): \Doctrine\ODM\PHPCR\Document\AbstractFile
Alors non c'est pas Rector (il n'est pas installé dans le projet) mais moi / phpstorm qui a refusé de faire l'import et je n'ai pas fait gaffe.

Il y avait la même chose dans Folder.php; c'est corrigé

2024-08-06 15:07 UTC, piero-hgt commented on src/Bundle/SonataPhpcrAdminIntegrationBundle/Admin/Routing/RouteAdmin.php
>          /** @var $route Route */
fait

2024-08-06 15:07 UTC, piero-hgt commented on src/Bundle/TreeBrowserBundle/Resources/build/webpack.config.js
> +            // },
ok supprimé

2024-08-06 15:07 UTC, piero-hgt commented on src/Bundle/TreeBrowserBundle/Resources/build/webpack.config.js
> +            // 'jquery-ui' : path.join(__dirname, 'node_modules/jquery-ui/dist/jquery-ui.js'),
supprimé aussi

2024-08-06 15:07 UTC, piero-hgt commented on src/Sonata/DoctrinePHPCRAdminBundle/Model/ModelManager.php
> +//    }
c'est nettoyé !

2024-08-06 15:08 UTC, piero-hgt commented
Je me suis remis sur les tests unitaires / fonctionnels. J'ai pu réparer certaines choses mais pas tout; ça m'a quand même permis de trouver des choses à corriger.

2024-08-27 12:58 UTC, patrick-benoit approved these changes

2024-08-27 12:59 UTC, merged